[workspace]
members = [
    "crates/runner",
    "crates/ponix-nats",
    "crates/ponix-clickhouse",
    "crates/ponix-all-in-one",
    "crates/goose",
    "crates/ponix-postgres",
    "crates/ponix-domain",
    "crates/ponix-grpc",
    "crates/ponix-payload",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Ponix Dev"]
license = "MIT"

[workspace.dependencies]
tokio = { version = "1.40", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
thiserror = "1.0"
prost = "0.13"
prost-types = "0.13"
xid = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
