apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    editable: true
    jsonData:
      host: ponix-clickhouse
      port: 9000
      protocol: native
      secure: false
      username: ponix
      defaultDatabase: ponix
      tlsSkipVerify: true
    secureJsonData:
      password: ponix
