name: Main

on:
  push:
    branches: [main]

permissions:
  contents: write # to create releases and push tags
  issues: write # to comment on issues
  pull-requests: write # to comment on PRs
  id-token: write # if using OIDC
  packages: write

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit-tests.yml
    secrets:
      BSR_TOKEN: ${{ secrets.BSR_TOKEN }}

  integration-tests:
    name: Integration Tests
    uses: ./.github/workflows/integration-tests.yml
    secrets:
      BSR_TOKEN: ${{ secrets.BSR_TOKEN }}

  e2e-tests:
    name: E2E Tests
    uses: ./.github/workflows/e2e-tests.yml
    secrets:
      BSR_TOKEN: ${{ secrets.BSR_TOKEN }}

  release:
    name: Release
    needs: [unit-tests, integration-tests, e2e-tests]
    uses: ./.github/workflows/release.yml
    secrets:
      BSR_TOKEN: ${{ secrets.BSR_TOKEN }}
